#!/bin/sh
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker --version'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker kill dev_api'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker rm dev_api'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker kill dev_elasticsearch'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker rm dev_elasticsearch'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker kill dev_db'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker rm dev_db'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker kill dev_pgadmin'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker rm dev_pgadmin'
sshpass -p $VM_PASSWORD ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST 'sudo docker-compose -f dev/docker-compose.yml up -d --build'
